

CREATE TABLE public.accounts (
    id uuid NOT NULL,
    account_name character varying(255) NOT NULL,
    account_type character varying(255) NOT NULL,
    balance numeric(19,4) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    currency character varying(255) NOT NULL,
    deleted_at timestamp(6) with time zone,
    is_active boolean NOT NULL,
    is_deleted boolean NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['SAVINGS'::character varying, 'CHECKING'::character varying, 'CASH'::character varying])::text[]))),
    CONSTRAINT accounts_currency_check CHECK (((currency)::text = ANY ((ARRAY['PHP'::character varying, 'USD'::character varying, 'JPY'::character varying])::text[])))
);



CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    details text,
    entity_id uuid NOT NULL,
    entity_type character varying(255) NOT NULL,
    ip_address character varying(255),
    performed_at timestamp(6) with time zone NOT NULL,
    user_id uuid NOT NULL
);



ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE public.loan_schedules (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    due_date date NOT NULL,
    interest_portion numeric(19,4) NOT NULL,
    payment_amount numeric(19,4) NOT NULL,
    payment_number integer NOT NULL,
    principal_portion numeric(19,4) NOT NULL,
    remaining_balance numeric(19,4) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    loan_id uuid NOT NULL,
    CONSTRAINT loan_schedules_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'MISSED'::character varying])::text[])))
);



CREATE TABLE public.loans (
    id uuid NOT NULL,
    annual_rate numeric(19,4) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    disbursed_at timestamp(6) with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    loan_name character varying(255) NOT NULL,
    maturity_date timestamp(6) with time zone NOT NULL,
    monthly_payment numeric(19,4) NOT NULL,
    principal numeric(19,4) NOT NULL,
    status character varying(255) NOT NULL,
    term_months integer NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    account_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT loans_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAID_OFF'::character varying, 'DEFAULTED'::character varying])::text[])))
);


CREATE TABLE public.refresh_tokens (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    device_info character varying(255),
    expires_at timestamp(6) with time zone NOT NULL,
    revoked boolean NOT NULL,
    token_hash character varying(255) NOT NULL,
    user_id uuid NOT NULL
);


CREATE TABLE public.transactions (
    id uuid NOT NULL,
    amount numeric(19,4) NOT NULL,
    category character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    description character varying(255),
    idempotency_key character varying(255) NOT NULL,
    is_deleted boolean NOT NULL,
    reference_number character varying(255) NOT NULL,
    transacted_at timestamp(6) with time zone NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    account_id uuid NOT NULL,
    CONSTRAINT transactions_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying, 'TRANSFER'::character varying, 'LOAN_PAYMENT'::character varying])::text[])))
);



CREATE TABLE public.users (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    deleted_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    google_id character varying(255),
    is_deleted boolean NOT NULL,
    password character varying(255) NOT NULL,
    provide character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT users_provide_check CHECK (((provide)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[])))
);



ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);




ALTER TABLE ONLY public.loan_schedules
    ADD CONSTRAINT loan_schedules_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.loans
    ADD CONSTRAINT loans_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);



ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uk96ogkdl6a4f18ybi32m3mi6h0 UNIQUE (reference_number);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT uke58eyb3fj0t2cl16q1ll436b7 UNIQUE (idempotency_key);


ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk20w7wsg13u9srbq3bd7chfxdh FOREIGN KEY (account_id) REFERENCES public.accounts(id);


ALTER TABLE ONLY public.loans
    ADD CONSTRAINT fk6xxlcjc0rqtn5nq28vjnx5t9d FOREIGN KEY (user_id) REFERENCES public.users(id);


ALTER TABLE ONLY public.loans
    ADD CONSTRAINT fkeja64hsi0agxgtppa7uccxrh4 FOREIGN KEY (account_id) REFERENCES public.accounts(id);



ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT fkk4alalwu62gj4tfbgfefll3tu FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES public.users(id);



ALTER TABLE ONLY public.loan_schedules
    ADD CONSTRAINT fkrxbpyqjoyiki2bj16h8y471aa FOREIGN KEY (loan_id) REFERENCES public.loans(id);



